name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: unwrap consul
      run: |
        cd bin/linux
        gunzip consul.gz

    - name: test consul binary
      run: |
        bin/linux/consul --version

    - name: unwrap dbdeployer
      run: |
        cd bin/linux
        gunzip dbdeployer.gz

    - name: deploy consul service
      run: |
        script/deploy-consul

    - name: start consul service
      run: |
        script/run-consul || sudo journalctl -u consul.service

    - name: test consul service
      run: |
        sudo systemctl status consul

    - name: test consul kv
      run: |
        echo "sleeping to allow consul to elect leader"
        sleep 3
        kvkey="ci/test/val"
        consul kv put $kvkey "$((16+1))"
        val="$(consul kv get $kvkey)"
        if [ "$val" == "17" ] ; then
          echo "Validated KV write+read"
        else
          echo "Failed validating consul KV"
          exit 1
        fi

    - name: unwrap consul-template
      run: |
        cd bin/linux
        gunzip consul-template.gz

    - name: deploy consul-template service
      run: |
        script/deploy-consul-template

    - name: test consul template binary
      run: |
        /usr/local/bin/consul-template --version

    - name: install haproxy
      run: |
        sudo apt-cache madison haproxy
        sudo apt-get update && sudo apt-get install -y haproxy

    - name: start consul-template service
      run: |
        script/run-consul-template || sudo journalctl -u consul-template.service

    - name: test consul-template service
      run: |
        sudo systemctl status consul-template || sudo journalctl -u consul-template.service

    - name: test consul-template template
      run: |
        sleep 5
        ls -l /tmp/haproxy.*
        cat /tmp/haproxy.*

    - name: deploy mysql replication
      run: |
        script/deploy-replication
