name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: deploy mysql replication
      run: |
        mkdir -p /home/runner/opt/mysql
        bin/linux/dbdeployer unpack mysql-tarballs/mysql-5.7.26.tar.xz
        bin/linux/dbdeployer deploy replication 5.7.26 -n 4 \
          --gtid \
          --my-cnf-options="report_host=ci-host" \
          --my-cnf-options="log_bin" \
          --my-cnf-options="log_slave_updates" \
          --my-cnf-options="performance_schema=0" \
          --my-cnf-options="innodb_buffer_pool_size=32M" \
          --my-cnf-options="master_info_repository=table" \
          --my-cnf-options="relay_log_info_repository=table" \
          --repl-crash-safe \
          --sandbox-directory="57"
