name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: unwrap consul
      run: |
        cd bin/linux
        gunzip consul.gz

    - name: test consul binary
      run: |
        bin/linux/consul --version

    - name: unwrap dbdeployer
      run: |
        cd bin/linux
        gunzip dbdeployer.gz

    - name: deploy consul service
      run: |
        script/deploy-consul

    - name: start consul service
      run: |
        sudo ls -l /etc/hosts
        sudo cat /etc/hosts
        script/run-consul

    - name: test consul service
      run: |
        sudo systemctl status consul

    - name: deploy mysql replication
      run: |
        script/deploy-replication
