name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: unwrap consul
      run: |
        cd bin/linux
        gunzip consul.gz

    - name: test consul binary
      run: |
        bin/linux/consul --version

    - name: unwrap dbdeployer
      run: |
        cd bin/linux
        gunzip dbdeployer.gz

    - name: deploy consul service
      run: |
        script/deploy-consul

    - name: start consul service
      run: |
        script/run-consul || sudo journalctl -u consul.service

    - name: test consul service
      run: |
        sudo systemctl status consul
        kvkey="ci/test/val"
        consul kv put $kvkey "$((16+1))"
        consul kv get $kvkey

    - name: unwrap consul-template
      run: |
        cd bin/linux
        gunzip consul-template.gz

    - name: deploy consul-template service
      run: |
        script/deploy-consul-template

    - name: test consul template binary
      run: |
        /usr/bin/consul-template --version

    - name: deploy mysql replication
      run: |
        script/deploy-replication
